### ISSUE TITLE
Nothing happens when using ctrl-u

### ISSUE THREAD

**Issue by mcstauer** [wesbaker/atom-docksend#3]
Hey wesbaker

Admittedly i am not a very skilled developer - mostly frontend and design - so my knowledge of bughunting is limited.

I just installed the docksend plugin as i'm moving from sublime text - but when running the short cut or rightclicking and choosing the docksend option nothing happens.

Is there a way i can test where this might go wrong?

Thanks
/Johan

**Comment by wesbaker** [comment]
Did you see my note under [usage](https://github.com/wesbaker/atom-docksend#usage)? If you have Emmet, or some other package that uses the same shortcut, you'll need to manually override the keyboard shortcut.

**Comment by mcstauer** [comment]
Thanks for your quick reply.

I had a look at the problem, and it seems it’s a bug in mac open. Since
Atom on mac provides string with spaces that are not escaped and mac-open
both double quotes and escapes spaces in paths, it results in a path not
found error.
So, this is just to let you know the source of the error lies in the
mac-open package, not in the docksend package.

Have a great day :)

On Wed, Nov 4, 2015 at 4:28 PM, Wes Baker notifications@github.com wrote:

> Did you see my note under usage
> https://github.com/wesbaker/atom-docksend#usage? If you have Emmet, or
> some other package that uses the same shortcut, you'll need to manually
> override the keyboard shortcut.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wesbaker/atom-docksend/issues/3#issuecomment-153762933
> .

## 

## 

Johan Staureby
Mob: 26744707
