### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by johnnyrains** [wesbaker/atom-docksend#5]
Hi I am using Emmet, and I did make changes to the keymap, but it is still not working for me.  Any ideas how I can trace this?  or get a little help?

**Comment by wesbaker** [comment]
What happens when you enable the [keybinding resolver](https://atom.io/packages/keybinding-resolver)?

**Comment by johnnyrains** [comment]
Hi Wes, 

keybinding resolver is enabled

I am not entirely sure what you want, but here’s a screen shot:

**Comment by wesbaker** [comment]
Hmm, I'm not seeing the screenshot. Can you post it directly in GitHub?

**Comment by johnnyrains** [comment]
Of course, here it is:
![screen shot 2016-06-14 at 8 09 49 pm](https://cloud.githubusercontent.com/assets/5685981/16066134/02b8d186-326e-11e6-8fd3-e9ae2041987d.png)

**Comment by wesbaker** [comment]
So what that's saying is that Emmet's keybinding (the one in green) is taking priority. Could you post your keymap? Alternatively if you don't use Emmet's keybinding should can go into Emmet's preferences and disable they keyboard shortcuts altogether (though that admittedly hobbles it a bit. Finally, your last choice is to change Docksend's keyboard shortcut to something different, you'd follow my instructions on setting an override and just choose a different key combination. 

Let me me know which of the three you'd like to do and I can help you out.

**Comment by johnnyrains** [comment]
I really don’t want to wast your time with this.

I have made “^ + 7” the key command, sort of per your instructions.  But this isn’t working either.  And neither is using the command from the manu itself.  Could it be an issue with Transmit?

**Comment by wesbaker** [comment]
Yeah, that makes me think Docksend isn't configured properly. What happens if you drop a file from the directory onto Transmit?

**Comment by johnnyrains** [comment]
First of all, you are very kind to spend you time with me on this.

When I grab a file from the tree view and drop it on the Transmit icon in the dock, nothing happens.  When I open a file from the remote server in Transmit, then save my work, Transmit will upload it.

As a side note, I used to use TextWrangler, and the key command (whatever it was) did what I am trying to do with Atom.

And here is a text grab of my keymap and keybindings.

Once again, thanks for your help.  

John

 http://www.fireflytheatre.com/       John Ullyatt - Webmaster
webmaster@fireflytheatre.com mailto:webmaster@fireflytheatre.com | www.fireflytheatre.com http://www.fireflytheatre.com/
twitter https://twitter.com/fireflyedmonton | facebook https://www.facebook.com/Firefly.Theatre.and.Circus
cell: (780) 242-5105

**Comment by wesbaker** [comment]
> When I grab a file from the tree view and drop it on the Transmit icon in the dock, nothing happens

So that's your problem. I'm guessing you don't have DockSend configured properly within Transmit. The way my package works is it basically mimics what you just did: dropping the file onto the Transmit icon. Transmit is taking care of all of the magic. DockSend looks at where the file is coming from and checks to see if that matches up with any of your FTP servers that have DockSend enabled. They explain it well here: https://panic.com/blog/15-secrets-of-transmit/

**Comment by johnnyrains** [comment]
My god, this is the stupidest thing.  I replaced my hd with an ssd, which has a new name.  Welcome to the idiot.

Thanks so much for your help, working fine.

John

 http://www.fireflytheatre.com/       John Ullyatt - Webmaster
webmaster@fireflytheatre.com mailto:webmaster@fireflytheatre.com | www.fireflytheatre.com http://www.fireflytheatre.com/
twitter https://twitter.com/fireflyedmonton | facebook https://www.facebook.com/Firefly.Theatre.and.Circus
cell: (780) 242-5105

**Comment by wesbaker** [comment]
John, no worries! I'm glad you got it working and I hope your day gets better 😄.
